blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://docs.sulu.io/
    about: Read the Sulu documentation
  - name: Community Support
    url: https://sulu.io/services-and-support
    about: Join the Sulu Slack community for questions and discussions
